# Standard Coconut evaluation configuration
# Requires 2 GPUs

project: coconut-dynamic
save_path: ckpts
name: "coconut-standard-eval"

only_eval: True

c_thought: 1
epochs_per_stage: 50
first_stage_epochs: 100
max_latent_stage: 4
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.1
model_id: configs/symbol-2layer-8head-768dim.json
load_model_path: ckpts/coconut-standard/checkpoint_350
seed: 0
resume: 349
bf16: False
train_path: data/prosqa_train_graph_4_coconut.json
val_path: data/prosqa_test_graph_4_coconut_shuffled.json
shuffle_nodes: True
reset_optimizer: True
batch_size_training: 256
debug: False
gradient_accumulation_steps: 1
num_epochs: 350
lr: !!float "1e-4"
weight_decay: 0.01